# Generated by Django 4.2.3 on 2023-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('aroma', models.FloatField(blank=True, null=True)),
                ('acidity', models.IntegerField(blank=True, null=True)),
                ('sweetness', models.IntegerField(blank=True, null=True)),
                ('body', models.IntegerField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('roasting_point', models.FloatField(blank=True, null=True)),
                ('roastery', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coupang_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coffee_bean_bean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeeBeanOrigin',
            fields=[
                ('country', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coffee_bean_origin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeeBeanOrigins',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coffee_bean_bean_origins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeeBeanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('user_nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('taste_satisfaction', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'coffee_bean_beanreview',
                'managed': False,
            },
        ),
    ]
