# Generated by Django 4.2.3 on 2023-07-20 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('coffee_bean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeInCart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coffee_in_cart',
                'managed': False,
            },
        ),
    ]
