baseline:
  config_name: baseline
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 64
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 128
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 100
    lr: 0.01
    weight_decay: 0.0005
    device: cuda
  topk: 4
  seed: 0
    
ver01:
  config_name: ver01
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 64
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 128
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 100
    lr: 0.001
    weight_decay: 0.0005
    device: cuda
  topk: 4
  seed: 0

ver02:
  config_name: ver02
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 64
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 128
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 500
    lr: 0.0005
    weight_decay: 0.00001
    device: cuda
  topk: 4
  seed: 0


ver03:
  config_name: ver03
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 64
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 128
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 1000
    lr: 0.00005
    weight_decay: 0.000001
    device: cuda
  topk: 4
  seed: 0

ver04:
  config_name: ver04
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 512
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 256
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 10000
    lr: 0.00005
    weight_decay: 0.000001
    device: cuda
  topk: 4
  seed: 0

ver05:
  config_name: ver05
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 128
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 256
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 10000
    lr: 0.0001
    weight_decay: 0.00001
    device: cuda
  topk: 4
  seed: 0


ver06:
  config_name: ver06
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 128
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 64
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 100
    lr: 0.0005
    weight_decay: 0.00001
    device: cuda
  topk: 4
  seed: 0


ver07:
  config_name: ver07
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 128
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 64
    dropout: 0.3
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 100
    lr: 0.00005
    weight_decay: 0.00001
    device: cuda
  topk: 4
  seed: 0


ver08:
  config_name: ver08
  feedback_type: explicit
  dataset: TorchDataset
  dataset_params:
    batch_size: 256
    shuffle: true
    test_ratio: 0.05
  model: AutoRec
  model_params:
    num_users: None
    num_items: None 
    num_hidden: 64
    dropout: 0.5
  trainer: DeepLearningTrainer
  trainer_params:
    epochs: 100
    lr: 0.00005
    weight_decay: 0.00001
    device: cuda
  topk: 4
  seed: 0
